import { FLEET_CAPABILITIES, type FleetCapability } from '../../../../shared/fleet.js';

import type { FleetCatalogChange, FleetCatalogDelta, FleetCatalogHealth, FleetCatalogHost, FleetCatalogPane, FleetCatalogProcessing, FleetCatalogProject, FleetCatalogSession, FleetCatalogSnapshot } from './types.js';

export class FleetCatalogParseError extends Error {
  constructor(message: string) { super(message); this.name = 'FleetCatalogParseError'; }
}
type Input = Readonly<Record<string, unknown>>;
export const MAX_FLEET_CATALOG_ROWS_PER_ENTITY = 1_000;
export const MAX_FLEET_CATALOG_DELTA_CHANGES = 4_000;
function fail(message: string): never { throw new FleetCatalogParseError(message); }
function object(value: unknown, name: string): Input { if (typeof value !== 'object' || value === null || Array.isArray(value)) fail(`${name} must be an object`); return Object.fromEntries(Object.entries(value)); }
function exact(value: Input, keys: readonly string[], name: string): void { if (Object.keys(value).some((key) => !keys.includes(key)) || keys.some((key) => !(key in value))) fail(`${name} fields are invalid`); }
function text(value: unknown, name: string, nullable = false): string | null { if (nullable && value === null) return null; if (typeof value !== 'string' || value.length === 0 || value.length > 4_096 || value.includes('\0')) fail(`${name} is invalid`); return value; }
function number(value: unknown, name: string, minimum = 0): number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < minimum) fail(`${name} is invalid`); return value; }
function bool(value: unknown, name: string): boolean { if (typeof value !== 'boolean') fail(`${name} is invalid`); return value; }
function list<T extends Readonly<{ readonly localId: string }>>(value: unknown, name: string, parse: (item: unknown) => T): readonly T[] { if (!Array.isArray(value) || value.length > MAX_FLEET_CATALOG_ROWS_PER_ENTITY) fail(`${name} is invalid`); const rows = value.map(parse); if (new Set(rows.map((row) => row.localId)).size !== rows.length) fail(`${name} contains duplicate rows`); return rows; }
function capabilities(value: unknown): readonly FleetCapability[] { if (!Array.isArray(value)) fail('capabilities is invalid'); const result: FleetCapability[] = []; for (const item of value) { const found = FLEET_CAPABILITIES.find((capability) => capability === item); if (found === undefined || result.includes(found)) fail('capabilities is invalid'); result.push(found); } return result; }
function host(value: unknown): FleetCatalogHost { const row = object(value, 'host'); exact(row, ['hostId', 'displayLabel', 'capabilities'], 'host'); return { hostId: text(row.hostId, 'hostId') ?? fail('hostId is invalid'), displayLabel: text(row.displayLabel, 'displayLabel') ?? fail('displayLabel is invalid'), capabilities: capabilities(row.capabilities) }; }
function project(value: unknown): FleetCatalogProject { const row = object(value, 'project'); exact(row, ['localId', 'path', 'displayName', 'isStarred'], 'project'); return { localId: text(row.localId, 'localId') ?? fail('localId is invalid'), path: text(row.path, 'path') ?? fail('path is invalid'), displayName: text(row.displayName, 'displayName') ?? fail('displayName is invalid'), isStarred: bool(row.isStarred, 'isStarred') }; }
function session(value: unknown): FleetCatalogSession { const row = object(value, 'session'); exact(row, ['localId', 'projectLocalId', 'provider', 'summary', 'lastActivityMs'], 'session'); return { localId: text(row.localId, 'localId') ?? fail('localId is invalid'), projectLocalId: text(row.projectLocalId, 'projectLocalId') ?? fail('projectLocalId is invalid'), provider: text(row.provider, 'provider') ?? fail('provider is invalid'), summary: typeof row.summary === 'string' ? row.summary : fail('summary is invalid'), lastActivityMs: number(row.lastActivityMs, 'lastActivityMs') }; }
function pane(value: unknown): FleetCatalogPane { const row = object(value, 'pane'); exact(row, ['localId', 'lane', 'tmuxName', 'tmux', 'process', 'kind', 'providerSessionId', 'activity', 'cwd', 'presence'], 'pane'); const tmux = object(row.tmux, 'tmux'); exact(tmux, ['socketPath', 'sessionId', 'windowId', 'paneId'], 'tmux'); let process = null; if (row.process !== null) { const generation = object(row.process, 'process'); exact(generation, ['pid', 'startedAtMs'], 'process'); process = { pid: number(generation.pid, 'pid', 1), startedAtMs: number(generation.startedAtMs, 'startedAtMs', 1) }; } if (row.lane !== 'external' && row.lane !== 'live') fail('lane is invalid'); if (row.presence !== 'present' && row.presence !== 'stale') fail('presence is invalid'); return { localId: text(row.localId, 'localId') ?? fail('localId is invalid'), lane: row.lane, tmuxName: text(row.tmuxName, 'tmuxName') ?? fail('tmuxName is invalid'), tmux: { socketPath: text(tmux.socketPath, 'socketPath') ?? fail('socketPath is invalid'), sessionId: text(tmux.sessionId, 'sessionId') ?? fail('sessionId is invalid'), windowId: text(tmux.windowId, 'windowId') ?? fail('windowId is invalid'), paneId: text(tmux.paneId, 'paneId') ?? fail('paneId is invalid') }, process, kind: text(row.kind, 'kind') ?? fail('kind is invalid'), providerSessionId: text(row.providerSessionId, 'providerSessionId', true), activity: text(row.activity, 'activity') ?? fail('activity is invalid'), cwd: text(row.cwd, 'cwd', true), presence: row.presence }; }
function processing(value: unknown): FleetCatalogProcessing { const row = object(value, 'processing'); exact(row, ['localId', 'provider', 'startedAtMs', 'lastSeq'], 'processing'); return { localId: text(row.localId, 'localId') ?? fail('localId is invalid'), provider: text(row.provider, 'provider') ?? fail('provider is invalid'), startedAtMs: number(row.startedAtMs, 'startedAtMs', 1), lastSeq: number(row.lastSeq, 'lastSeq') }; }
function laneHealth(value: unknown) { const row = object(value, 'lane health'); exact(row, ['ok', 'lastOkRevision', 'consecutiveFailures'], 'lane health'); return { ok: bool(row.ok, 'ok'), lastOkRevision: row.lastOkRevision === null ? null : number(row.lastOkRevision, 'lastOkRevision'), consecutiveFailures: number(row.consecutiveFailures, 'consecutiveFailures') }; }
function health(value: unknown): FleetCatalogHealth { const row = object(value, 'health'); exact(row, ['external', 'live'], 'health'); return { external: laneHealth(row.external), live: laneHealth(row.live) }; }
function change(value: unknown): FleetCatalogChange { const row = object(value, 'change'); exact(row, ['op', 'entity', 'row'], 'change'); if (row.op !== 'upsert' && row.op !== 'remove') fail('change op is invalid'); switch (row.entity) { case 'project': return { op: row.op, entity: row.entity, row: project(row.row) }; case 'session': return { op: row.op, entity: row.entity, row: session(row.row) }; case 'pane': return { op: row.op, entity: row.entity, row: pane(row.row) }; case 'processing': return { op: row.op, entity: row.entity, row: processing(row.row) }; default: return fail('change entity is invalid'); } }
export function parseFleetCatalogSnapshot(value: unknown): FleetCatalogSnapshot { const row = object(value, 'snapshot'); exact(row, ['epoch', 'revision', 'host', 'projects', 'sessions', 'panes', 'health', 'processing'], 'snapshot'); return { epoch: text(row.epoch, 'epoch') ?? fail('epoch is invalid'), revision: number(row.revision, 'revision', 1), host: host(row.host), projects: list(row.projects, 'projects', project), sessions: list(row.sessions, 'sessions', session), panes: list(row.panes, 'panes', pane), health: health(row.health), processing: list(row.processing, 'processing', processing) }; }
export function parseFleetCatalogDelta(value: unknown): FleetCatalogDelta { const row = object(value, 'delta'); const keys = row.host === undefined ? ['epoch', 'prevRevision', 'revision', 'changes', 'health'] : ['epoch', 'prevRevision', 'revision', 'host', 'changes', 'health']; exact(row, keys, 'delta'); const parsedHost = row.host === undefined ? {} : { host: host(row.host) }; if (!Array.isArray(row.changes) || row.changes.length > MAX_FLEET_CATALOG_DELTA_CHANGES) fail('changes is invalid'); return { epoch: text(row.epoch, 'epoch') ?? fail('epoch is invalid'), prevRevision: number(row.prevRevision, 'prevRevision'), revision: number(row.revision, 'revision', 1), ...parsedHost, changes: row.changes.map(change), health: health(row.health) }; }
