export const PRODUCT_NAME = 'ChatMux';
export const PRODUCT_TOKEN = 'chatmux';
export const PACKAGE_NAME = PRODUCT_TOKEN;
export const CLI_NAME = PRODUCT_TOKEN;
export const DATA_ROOT = '~/.chatmux';
export const SYSTEMD_SERVICE_NAME = 'chatmux.service';
export const URL_SCHEME = 'chatmux';
export const URL_SCHEME_URL = 'chatmux://';
export const ENVIRONMENT_PREFIX = 'CHATMUX_';
export const DESKTOP_APP_ID = 'app.chatmux.desktop';
export const ARTIFACT_PREFIX = 'chatmux-';
export const REPOSITORY_SLUG = 'devswha/chatmux';
export const REPOSITORY_URL = 'https://github.com/devswha/chatmux';
export const ISSUES_URL = 'https://github.com/devswha/chatmux/issues';
export const RELEASES_URL = 'https://github.com/devswha/chatmux/releases';
export const AUTHOR = 'devswha and ChatMux contributors';
export const NODE_ENGINE_RANGE = '>=22.22.2 <23 || >=24.15.0 <25';
